name: jetleaf_lang
description: This library exposes extended Dart primitives, collections, optional types, I/O streams, date/time utilities, math types, regex, and more.
version: 1.0.0

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_lang

topics:
- IO
- Collections
- Primitives
- Helpers

keywords:
- IO
- Collections
- Primitives
- Helpers

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.0.0
  dart_internal: ^0.2.15
  meta: ^1.17.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0
publish_to: https://onepub.dev/api/fahnhnofly/
