name: jetleaf_lang
description: Language utilities for JetLeaf â€” provides extended Dart primitives, collections, I/O, date/time, math, and regex types.
version: 1.0.4

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_lang
issue_tracker: https://github.com/jetleaf/jetleaf_lang/issues
documentation: https://jetleaf.hapnium.com/docs/lang

topics:
  - language
  - primitives
  - collections
  - jetleaf
  - utilities

keywords:
  - jetleaf
  - language
  - primitives
  - collections
  - utilities

environment:
  sdk: ^3.9.0

dependencies:
  analyzer: ^8.0.0
  dart_internal: ^0.2.15
  meta: ^1.17.0
  path: ^1.9.1
  jetleaf_build: ^1.0.3

dev_dependencies:
  test: ^1.21.0
  lints: ^6.0.0