name: jetleaf_lang
description: Language utilities for JetLeaf â€” provides extended Dart primitives, collections, I/O, date/time, math, and regex types.
version: 1.1.2

homepage: https://jetleaf.hapnium.com
repository: https://github.com/jetleaf/jetleaf_lang
issue_tracker: https://github.com/jetleaf/jetleaf_lang/issues
documentation: https://jetleaf.hapnium.com/docs/lang

topics:
  - language
  - primitives
  - collections
  - jetleaf
  - utilities

keywords:
  - jetleaf
  - language
  - primitives
  - collections
  - utilities

environment:
  sdk: ^3.9.0

dependencies:
  dart_internal: ^0.2.17
  meta: ^1.17.0
  path: ^1.9.1
  jetleaf_build: ^1.1.1

dev_dependencies:
  test: ^1.28.0
  lints: ^6.0.0